
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRLIT = 47;
  public static final int BOOLLIT = 42;
  public static final int FORALL = 40;
  public static final int SEQ = 22;
  public static final int POW = 15;
  public static final int CHAR = 6;
  public static final int GTHANEQ = 18;
  public static final int LTHANEQ = 17;
  public static final int EQUALS = 19;
  public static final int LPAREN = 50;
  public static final int BADCHAR = 62;
  public static final int INT = 3;
  public static final int ENDDO = 39;
  public static final int MINUS = 12;
  public static final int RPAREN = 51;
  public static final int NOT = 8;
  public static final int AND = 9;
  public static final int INTLIT = 44;
  public static final int APPEND = 24;
  public static final int LTHAN = 16;
  public static final int NEQUALS = 20;
  public static final int IN = 26;
  public static final int OR = 10;
  public static final int TDEF = 27;
  public static final int COMMA = 57;
  public static final int BOOL = 2;
  public static final int SEMICOL = 58;
  public static final int DIV = 14;
  public static final int RAT = 4;
  public static final int PLUS = 11;
  public static final int MAIN = 60;
  public static final int ASSIGN = 52;
  public static final int IF = 32;
  public static final int DOT = 61;
  public static final int ID = 48;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int RATLIT = 45;
  public static final int error = 1;
  public static final int FDEF = 28;
  public static final int VOID = 7;
  public static final int FLOATLIT = 46;
  public static final int LBRACK = 53;
  public static final int TOP = 23;
  public static final int COL = 59;
  public static final int TIMES = 13;
  public static final int CHARLIT = 43;
  public static final int ENDIF = 36;
  public static final int LBRACE = 55;
  public static final int DICT = 21;
  public static final int ELSE = 34;
  public static final int RBRACK = 54;
  public static final int READ = 30;
  public static final int WHILE = 37;
  public static final int FLOAT = 5;
  public static final int RBRACE = 56;
  public static final int THEN = 35;
  public static final int LEN = 25;
  public static final int ALIAS = 29;
  public static final int RANGBR = 49;
  public static final int ELIF = 33;
  public static final int DO = 38;
  public static final int PRINT = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "INT",
  "RAT",
  "FLOAT",
  "CHAR",
  "VOID",
  "NOT",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "LTHAN",
  "LTHANEQ",
  "GTHANEQ",
  "EQUALS",
  "NEQUALS",
  "DICT",
  "SEQ",
  "TOP",
  "APPEND",
  "LEN",
  "IN",
  "TDEF",
  "FDEF",
  "ALIAS",
  "READ",
  "PRINT",
  "IF",
  "ELIF",
  "ELSE",
  "THEN",
  "ENDIF",
  "WHILE",
  "DO",
  "ENDDO",
  "FORALL",
  "RETURN",
  "BOOLLIT",
  "CHARLIT",
  "INTLIT",
  "RATLIT",
  "FLOATLIT",
  "STRLIT",
  "ID",
  "RANGBR",
  "LPAREN",
  "RPAREN",
  "ASSIGN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "SEMICOL",
  "COL",
  "MAIN",
  "DOT",
  "BADCHAR"
  };
}

